### ISSUE TITLE
Download links are dead

### ISSUE THREAD

**Issue by rtran9** [california-civic-data-coalition/californiacivicdata.org#20]
`https://calaccess.californiacivicdata.org/downloads/`

**Comment by aboutaaron** [comment]
Thanks for flagging. I think our download domain did but our S3 uploads are working. You can access them in the short term using the full S3 URL: `https://django-calaccess.s3-us-west-2.amazonaws.com/`

For example, the latest archive is at https://django-calaccess.s3-us-west-2.amazonaws.com/flat_2020-02-28_10-17-21.zip

**Comment by aboutaaron** [comment]
Moved this issue to the appropriate repo
